file(STRINGS "${INPUT_FILE}" LINES)
set(OUTPUT "")
foreach(LINE IN LISTS LINES)
    string(FIND "${LINE}" "prefer " POS)
    if(POS EQUAL -1)
        string(APPEND OUTPUT "${LINE}\n")
    endif()
endforeach()
file(WRITE "${OUTPUT_FILE}" "${OUTPUT}")
